version: "3"
services:
  php-api:
    build: "./"
    volumes:
      - "./src:/var/www/html"
    ports:
      - "3000:80"
    networks:
      - mysql_network
  mysql:
    image: "mariadb:latest"
    restart: "unless-stopped"
    ports:
      - "3306:3306"
    env_file: .env
    networks:
      - mysql_network
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    restart: always
    ports:
      - "8001:80"
    depends_on:
      - "mysql"
    env_file: .env
    networks:
      - mysql_network

volumes:
  mysql_db_volume:
networks:
  mysql_network:
